"""learner_profiles

Revision ID: c680843e1e0a
Revises: fed9f2ac9d04
Create Date: 2026-06-02 14:47:41.310708
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c680843e1e0a'
down_revision = 'fed9f2ac9d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=True),
    sa.Column('correction_intensity', sa.String(length=16), nullable=False),
    sa.Column('accent', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_profiles')
    # ### end Alembic commands ###
