"""missions

Revision ID: fb4423db1c92
Revises: f3a4b2c1d0e9
Create Date: 2026-07-28 10:56:19.696256
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fb4423db1c92'
down_revision = 'f3a4b2c1d0e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('likely_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_user_id'), 'missions', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sessions_mission_id'), 'sessions', ['mission_id'], unique=False)
    # Name the FK explicitly so downgrade can drop it by name (Alembic emits
    # None otherwise, which fails on Postgres).
    op.create_foreign_key(
        'fk_sessions_mission_id_missions',
        'sessions', 'missions', ['mission_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_mission_id_missions', 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_mission_id'), table_name='sessions')
    op.drop_column('sessions', 'mission_id')
    op.drop_index(op.f('ix_missions_user_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
