"""add last_activity_at to sessions (#119)

Revision ID: fc233850563a
Revises: 02cf10ba6ab7
Create Date: 2026-07-31 12:25:28.846953
"""

import sqlalchemy as sa
from alembic import op

revision = "fc233850563a"
down_revision = "02cf10ba6ab7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "last_activity_at")
    # ### end Alembic commands ###
