"""initial users

Revision ID: fed9f2ac9d04
Revises: 
Create Date: 2026-06-02 14:43:42.387361
"""
from alembic import op
import sqlalchemy as sa


revision = 'fed9f2ac9d04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('native_language', sa.String(length=8), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=True),
    sa.Column('minutes_used_today', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
